# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-pgsql-stig-v-233616r617333-audit-pgsql-directory
  namespace: default # Change your namespace
spec:
  tags: ["STIG", "PostgreSQL"]
  message: "Notification! postgresql data has been accessed"
  selector:
    matchLabels:
       container: postgresql-1 # Change your match labels
  process:
    action: Audit
    severity: 6
    matchDirectories:
      - dir: /var/lib/postgresql/data/
        fromSource:
          - path: /usr/lib/postgresql/14/bin/postgres
        recursive: true
