# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-pgsql-stig-v-233616r617333-non-pgsql-binaries
  namespace: default # Change your namespace
spec:
  tags: ["STIG", "PostgreSQL"]
  message: "Notification! postgresql data has been accessed"
  selector:
    matchLabels:
       container: postgresql-1 # Change your match labels
  process:
    severity: 6
    matchPaths:
      - path: /bin/mv
      - path: /bin/cp
      - path: /bin/rm
      - path: /bin/rmdir
      - path: /bin/ls
    action: Audit
